name: DartleC Build

on: [push]

permissions:
  statuses: write
  checks: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Install C Compiler on Windows
        if: runner.os == 'Windows'
        run: choco install llvm
      - name: Build
        shell: bash
        run: dart dartle.dart
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Dartle Tests
          path: build/*.json
          reporter: dart-json
